spring:
  database:
    url: jdbc:h2:top://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format-sql: true

logging:
  level:
    ort.hibernate.SQL: debug